### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by MurilloNFaria** [BrenoHenrike/Skua#28]
hey guys, i'm getting that crash everytime i try to open skua manager on 1.2 versions, any fix? i'm using older versions to play but i cant use any script
![imagem_2023-02-08_202300416](https://user-images.githubusercontent.com/121845890/217674207-eabb937f-20be-41ef-8dfb-55d7804c3a67.png)

**Comment by BrenoHenrike** [comment]
Did you run the installer? it should create those folders.

**Comment by MurilloNFaria** [comment]
> Did you run the installer? it should create those folders.

Yes, and to make sure i uninstalled and installed a couple of times, but still didn't work since the first time, i tried to install 1.2 and 1.2.1

**Comment by BrenoHenrike** [comment]
Only thing that comes to my mind is that somehow you don't have the Documents folder, which is odd as Windows knows which one it is independent of system language. Can you confirm it?

**Comment by MurilloNFaria** [comment]
I'll assume you're talking about the default Documents folder that Windows creates automatically on every PC, so I have it. I tried to search the path of the error, which is: "C:\Users\'user'\Documents\Skua" and It seems like I don't have the Skua folder.
I searched as Documentos because my PC is in PT_BR.
![image](https://user-images.githubusercontent.com/121845890/220221257-eaf4a17a-ae1b-4711-a7ca-67a94902e748.png)

**Comment by MurilloNFaria** [comment]
Somehow i found a way to open the client.
I created the missing Skua folder on Documents and copied and pasted on it the archives inside Skua_Modules folder of the 1.1.4.1 version, and it worked!
But now i get an error saying that CompiledScripts.cs is denied
![image](https://user-images.githubusercontent.com/121845890/221394953-4e5ee5ea-6d4f-4940-8942-1a9bb9deb9dc.png)
There are two solutions that came to my mind, first is to someone that has it installed correctly send me the archives of the Skua folder of the 1.2.1.0 version via e-mail or something like google drive, and the second is that someone helps me to fix that error.
I'm really trying to fix it by myself, but i feel like i can't do more after that, i hope you can help me.

**Comment by BrenoHenrike** [comment]
Solved by running the installer as admin
