### ISSUE TITLE
Can developers get all the in-game item data and export a list?

### ISSUE THREAD

**Issue by Quannh1511** [BrenoHenrike/Skua#3]
I'm looking for all the in-game item data, can the developers do this? I use those data to compare with the items on the "https://aqwwiki.wikidot.com" page to find the wrong items and fix it. Since the data in the game is correct, it will be easy to compare. If the developers can do this, I want the game items to be listed and updated daily, and how can I make that list public so I can get it daily? without having to go through the bot client to get.

Thank you.

**Comment by slypy** [comment]
No we don't. This is kinda very severe violation.
