### ISSUE TITLE
Suporte a servidores privado

### ISSUE THREAD

**Issue by Luanvictordev** [BrenoHenrike/Skua#4]
É possível que vocês adicionem um sistema que dê suporte a servidores privados (private server) de aqw? ou lançarem algum tutorial de como fazer a adaptação do código para funcionar em outros, algo do gênero. 
Desde já meus parabéns pela iniciativa, e que "trainer" foda que você fez mano, tu é foda!

**Comment by slypy** [comment]
Possible but we are not going to make it...
