### ISSUE TITLE
erro 

### ISSUE THREAD

**Issue by blublak** [BrenoHenrike/Skua#42]
estou com esse erro 
![ererr](https://user-images.githubusercontent.com/126425315/221448515-ae788265-99c4-4781-b3a3-e475c1a7ff88.png)
em qualquer bot que coloco fica assim e começou hoje de tarde após sair e entrar novamente no bot

**Comment by d3lfs** [comment]
Open this in [Skua Scripts](https://github.com/BrenoHenrike/Scripts) repository not here.
