### ISSUE TITLE
Git Hub api limit reached?

### ISSUE THREAD

**Issue by Bio8199** [BrenoHenrike/Skua#5]
I am unable to get any scripts, and I constantly get a github api limit reached error, even though I did the github authenticator... please help.

https://user-images.githubusercontent.com/121003792/208354027-d8eb6be5-a958-4909-b9f7-5bacaa7c190b.png

**Comment by ubergn00b** [comment]
I'm having trouble accessing scripts as well, and am also getting this notification

**Comment by d3lfs** [comment]
See: 95227049d94ef5c12da6ca4c2bc020d116678258
